#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d mus web code dev note 六 七 八 九  

bspc config border_width         1
bspc config focused_border_color "#de9649"
bspc config window_gap           5
bspc config top_padding 	 26

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a '*:*:Picture-in-Picture' state=floating

fcitx -d &
~/.config/polybar/launch.sh &
feh ~/Pictures/Wallpapers/bruegel.jpg --bg-fill &
setxkbmap us &
setxkbmap -option caps:escape,shift:both_capslock
